name: tylo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  #Firebase
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  google_sign_in: ^6.2.1
  firebase_messaging: ^15.0.3

  connectivity_plus: ^6.0.3
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  file_picker: ^8.0.6
  fluttertoast: ^8.2.6
  pinput: ^5.0.0
  sms_autofill: ^2.4.0
  ionicons: ^0.2.2

  agora_rtc_engine: ^6.3.2
  agora_uikit: ^1.3.10

  flutter_speed_dial: ^7.0.0
  path_provider: ^2.1.3
  cached_network_image: ^3.3.1
  flutter_contacts: ^1.1.8
  social_media_recorder: ^1.1.13

  shared_preferences: ^2.2.3
  share_plus: ^9.0.0
  url_launcher: ^6.3.0
  get_it: ^7.7.0
  emoji_picker_flutter: ^2.2.0
  intl_phone_field: ^3.2.0
  audio_waveforms: ^1.0.5
  dartz: ^0.10.1
  cached_video_player_plus: ^3.0.2
  ffmpeg_kit_flutter: ^6.0.3
  intl: ^0.18.1
  set_ringtone: ^1.0.0
  flutter_local_notifications: ^17.2.1+2
  flutter_bloc: ^8.1.6
  dio: ^5.5.0+1
  just_audio: ^0.9.39
  percent_indicator: ^4.2.3
  flutter_chat_bubble: ^2.0.2
  gal: ^2.3.0
  flutter_secure_storage: ^9.2.2
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  fonts:
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/ReadexPro.ttf
          weight: 700

  assets:
    - assets/images/
    - assets/images/app_logo/
    - assets/languages/
    - assets/fonts/
    - assets/audio/
