List<Map<String, dynamic>> countryCodes =
[
  {"name": "AF", "country": "Afghanistan", "code": "0093"},
  {"name": "AL", "country": "Albania", "code": "00355"},
  {"name": "DZ", "country": "Algeria", "code": "00213"},
  {"name": "AD", "country": "Andorra", "code": "376"},
  {"name": "AO", "country": "Angola", "code": "00244"},
  {"name": "AG", "country": "Antigua and Barbuda", "code": "001268"},
  {"name": "AR", "country": "Argentina", "code": "0054"},
  {"name": "AM", "country": "Armenia", "code": "00374"},
  {"name": "AU", "country": "Australia", "code": "00061"},
  {"name": "AT", "country": "Austria", "code": "00043"},
  {"name": "AZ", "country": "Azerbaijan", "code": "00994"},
  {"name": "BS", "country": "Bahamas", "code": "001242"},
  {"name": "BH", "country": "Bahrain", "code": "00973"},
  {"name": "BD", "country": "Bangladesh", "code": "00880"},
  {"name": "BB", "country": "Barbados", "code": "001246"},
  {"name": "BY", "country": "Belarus", "code": "00375"},
  {"name": "BE", "country": "Belgium", "code": "00032"},
  {"name": "BZ", "country": "Belize", "code": "00501"},
  {"name": "BJ", "country": "Benin", "code": "00229"},
  {"name": "BT", "country": "Bhutan", "code": "00975"},
  {"name": "BO", "country": "Bolivia", "code": "00591"},
  {"name": "BA", "country": "Bosnia and Herzegovina", "code": "00387"},
  {"name": "BW", "country": "Botswana", "code": "00267"},
  {"name": "BR", "country": "Brazil", "code": "0055"},
  {"name": "BN", "country": "Brunei Darussalam", "code": "00673"},
  {"name": "BG", "country": "Bulgaria", "code": "00359"},
  {"name": "BF", "country": "Burkina Faso", "code": "00226"},
  {"name": "BI", "country": "Burundi", "code": "00257"},
  {"name": "KH", "country": "Cambodia", "code": "00855"},
  {"name": "CM", "country": "Cameroon", "code": "00237"},
  {"name": "CA", "country": "Canada", "code": "001"},
  {"name": "CV", "country": "Cape Verde", "code": "00238"},
  {"name": "CF", "country": "Central African Republic", "code": "00236"},
  {"name": "TD", "country": "Chad", "code": "00235"},
  {"name": "CL", "country": "Chile", "code": "00056"},
  {"name": "CN", "country": "China", "code": "0086"},
  {"name": "CO", "country": "Colombia", "code": "00057"},
  {"name": "KM", "country": "Comoros", "code": "00269"},
  {"name": "CG", "country": "Congo", "code": "00242"},
  {"name": "CD", "country": "Democratic Republic of the Congo", "code": "00243"},
  {"name": "CR", "country": "Costa Rica", "code": "00506"},
  {"name": "HR", "country": "Croatia", "code": "00385"},
  {"name": "CU", "country": "Cuba", "code": "00053"},
  {"name": "CY", "country": "Cyprus", "code": "00357"},
  {"name": "CZ", "country": "Czech Republic", "code": "00420"},
  {"name": "DK", "country": "Denmark", "code": "00045"},
  {"name": "DJ", "country": "Djibouti", "code": "00253"},
  {"name": "DM", "country": "Dominica", "code": "001767"},
  {"name": "DO", "country": "Dominican Republic", "code": "00809"},
  {"name": "EC", "country": "Ecuador", "code": "00593"},
  {"name": "EG", "country": "Egypt", "code": "002"},
  {"name": "SV", "country": "El Salvador", "code": "503"},
  {"name": "GQ", "country": "Equatorial Guinea", "code": "00240"},
  {"name": "ER", "country": "Eritrea", "code": "00291"},
  {"name": "EE", "country": "Estonia", "code": "00372"},
  {"name": "ET", "country": "Ethiopia", "code": "00251"},
  {"name": "FJ", "country": "Fiji", "code": "00679"},
  {"name": "FI", "country": "Finland", "code": "00358"},
  {"name": "FR", "country": "France", "code": "00033"},
  {"name": "GA", "country": "Gabon", "code": "00241"},
  {"name": "GM", "country": "Gambia", "code": "00220"},
  {"name": "GE", "country": "Georgia", "code": "00995"},
  {"name": "DE", "country": "Germany", "code": "00049"},
  {"name": "GH", "country": "Ghana", "code": "00233"},
  {"name": "GR", "country": "Greece", "code": "0030"},
  {"name": "GD", "country": "Grenada", "code": "001473"},
  {"name": "GT", "country": "Guatemala", "code": "00502"},
  {"name": "GN", "country": "Guinea", "code": "00224"},
  {"name": "GW", "country": "Guinea-Bissau", "code": "00245"},
  {"name": "GY", "country": "Guyana", "code": "00592"},
  {"name": "HT", "country": "Haiti", "code": "00509"},
  {"name": "HN", "country": "Honduras", "code": "00504"},
  {"name": "HU", "country": "Hungary", "code": "0036"},
  {"name": "IS", "country": "Iceland", "code": "00354"},
  {"name": "IN", "country": "India", "code": "0091"},
  {"name": "ID", "country": "Indonesia", "code": "0062"},
  {"name": "IR", "country": "Iran", "code": "0098"},
  {"name": "IQ", "country": "Iraq", "code": "00964"},
  {"name": "IE", "country": "Ireland", "code": "00353"},
  {"name": "IL", "country": "Israel", "code": "00972"},
  {"name": "IT", "country": "Italy", "code": "0039"},
  {"name": "JM", "country": "Jamaica", "code": "00876"},
  {"name": "JP", "country": "Japan", "code": "0081"},
  {"name": "JO", "country": "Jordan", "code": "00962"},
  {"name": "KZ", "country": "Kazakhstan", "code": "007"},
  {"name": "KE", "country": "Kenya", "code": "00254"},
  {"name": "KI", "country": "Kiribati", "code": "00686"},
  {"name": "KP", "country": "North Korea", "code": "00850"},
  {"name": "KR", "country": "South Korea", "code": "0082"},
  {"name": "KW", "country": "Kuwait", "code": "00965"},
  {"name": "KG", "country": "Kyrgyzstan", "code": "00996"},
  {"name": "LA", "country": "Laos", "code": "00856"},
  {"name": "LV", "country": "Latvia", "code": "00371"},
  {"name": "LB", "country": "Lebanon", "code": "00961"},
  {"name": "LS", "country": "Lesotho", "code": "00266"},
  {"name": "LR", "country": "Liberia", "code": "00231"},
  {"name": "LY", "country": "Libya", "code": "00218"},
  {"name": "LI", "country": "Liechtenstein", "code": "00423"},
  {"name": "LT", "country": "Lithuania", "code": "00370"},
  {"name": "LU", "country": "Luxembourg", "code": "00352"},
  {"name": "MG", "country": "Madagascar", "code": "00261"},
  {"name": "MW", "country": "Malawi", "code": "00265"},
  {"name": "MY", "country": "Malaysia", "code": "0060"},
  {"name": "MV", "country": "Maldives", "code": "00960"},
  {"name": "ML", "country": "Mali", "code": "00223"},
  {"name": "MT", "country": "Malta", "code": "00356"},
  {"name": "MH", "country": "Marshall Islands", "code": "00692"},
  {"name": "MR", "country": "Mauritania", "code": "00222"},
  {"name": "MU", "country": "Mauritius", "code": "00230"},
  {"name": "MX", "country": "Mexico", "code": "0052"},
  {"name": "FM", "country": "Micronesia", "code": "00691"},
  {"name": "MD", "country": "Moldova", "code": "00373"},
  {"name": "MC", "country": "Monaco", "code": "00377"},
  {"name": "MN", "country": "Mongolia", "code": "00976"},
  {"name": "ME", "country": "Montenegro", "code": "00382"},
  {"name": "MA", "country": "Morocco", "code": "00212"},
  {"name": "MZ", "country": "Mozambique", "code": "00258"},
  {"name": "MM", "country": "Myanmar", "code": "0095"},
  {"name": "NA", "country": "Namibia", "code": "00264"},
  {"name": "NR", "country": "Nauru", "code": "00674"},
  {"name": "NP", "country": "Nepal", "code": "00977"},
  {"name": "NL", "country": "Netherlands", "code": "0031"},
  {"name": "NZ", "country": "New Zealand", "code": "0064"},
  {"name": "NI", "country": "Nicaragua", "code": "00505"},
  {"name": "NE", "country": "Niger", "code": "00227"},
  {"name": "NG", "country": "Nigeria", "code": "00234"},
  {"name": "NO", "country": "Norway", "code": "0047"},
  {"name": "OM", "country": "Oman", "code": "00968"},
  {"name": "PK", "country": "Pakistan", "code": "0092"},
  {"name": "PW", "country": "Palau", "code": "00680"},
  {"name": "PS", "country": "Palestine", "code": "00970"},
  {"name": "PA", "country": "Panama", "code": "00507"},
  {"name": "PG", "country": "Papua New Guinea", "code": "00675"},
  {"name": "PY", "country": "Paraguay", "code": "00595"},
  {"name": "PE", "country": "Peru", "code": "051"},
  {"name": "PH", "country": "Philippines", "code": "0063"},
  {"name": "PL", "country": "Poland", "code": "0048"},
  {"name": "PT", "country": "Portugal", "code": "00351"},
  {"name": "QA", "country": "Qatar", "code": "00974"},
  {"name": "RO", "country": "Romania", "code": "0040"},
  {"name": "RU", "country": "Russia", "code": "007"},
  {"name": "RW", "country": "Rwanda", "code": "00250"},
  {"name": "KN", "country": "Saint Kitts and Nevis", "code": "001869"},
  {"name": "LC", "country": "Saint Lucia", "code": "001758"},
  {"name": "VC", "country": "Saint Vincent and the Grenadines", "code": "001784"},
  {"name": "WS", "country": "Samoa", "code": "00685"},
  {"name": "SM", "country": "San Marino", "code": "00378"},
  {"name": "ST", "country": "Sao Tome and Principe", "code": "00239"},
  {"name": "SA", "country": "Saudi Arabia", "code": "00966"},
  {"name": "SN", "country": "Senegal", "code": "00221"},
  {"name": "RS", "country": "Serbia", "code": "00381"},
  {"name": "SC", "country": "Seychelles", "code": "00248"},
  {"name": "SL", "country": "Sierra Leone", "code": "00232"},
  {"name": "SG", "country": "Singapore", "code": "0065"},
  {"name": "SK", "country": "Slovakia", "code": "00421"},
  {"name": "SI", "country": "Slovenia", "code": "00386"},
  {"name": "SB", "country": "Solomon Islands", "code": "00677"},
  {"name": "SO", "country": "Somalia", "code": "00252"},
  {"name": "ZA", "country": "South Africa", "code": "0027"},
  {"name": "SS", "country": "South Sudan", "code": "00211"},
  {"name": "ES", "country": "Spain", "code": "0034"},
  {"name": "LK", "country": "Sri Lanka", "code": "0094"},
  {"name": "SD", "country": "Sudan", "code": "00249"},
  {"name": "SR", "country": "Suriname", "code": "00597"},
  {"name": "SZ", "country": "Eswatini", "code": "00268"},
  {"name": "SE", "country": "Sweden", "code": "0046"},
  {"name": "CH", "country": "Switzerland", "code": "0041"},
  {"name": "SY", "country": "Syria", "code": "00963"},
  {"name": "TJ", "country": "Tajikistan", "code": "00992"},
  {"name": "TZ", "country": "Tanzania", "code": "00255"},
  {"name": "TH", "country": "Thailand", "code": "0066"},
  {"name": "TL", "country": "Timor-Leste", "code": "00670"},
  {"name": "TG", "country": "Togo", "code": "00228"},
  {"name": "TO", "country": "Tonga", "code": "00676"},
  {"name": "TT", "country": "Trinidad and Tobago", "code": "001868"},
  {"name": "TN", "country": "Tunisia", "code": "00216"},
  {"name": "TR", "country": "Turkey", "code": "0090"},
  {"name": "TM", "country": "Turkmenistan", "code": "00993"},
  {"name": "TV", "country": "Tuvalu", "code": "00688"},
  {"name": "UG", "country": "Uganda", "code": "00256"},
  {"name": "UA", "country": "Ukraine", "code": "00380"},
  {"name": "AE", "country": "United Arab Emirates", "code": "00971"},
  {"name": "GB", "country": "United Kingdom", "code": "0044"},
  {"name": "US", "country": "United States", "code": "001"},
  {"name": "UY", "country": "Uruguay", "code": "00598"},
  {"name": "UZ", "country": "Uzbekistan", "code": "00998"},
  {"name": "VU", "country": "Vanuatu", "code": "00678"},
  {"name": "VE", "country": "Venezuela", "code": "0058"},
  {"name": "VN", "country": "Vietnam", "code": "0084"},
  {"name": "YE", "country": "Yemen", "code": "00967"},
  {"name": "ZM", "country": "Zambia", "code": "00260"},
  {"name": "ZW", "country": "Zimbabwe", "code": "00263"}
];